name: Bina
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
  hexcolor: 
  lottie:
  rflutter_alert:
  double_back_to_close_app: 
  # modal_bottom_sheet:
  # adaptive_action_sheet:
  # country_pickers: ^1.3.0
  geolocator: ^6.2.0
  geocoder: ^0.2.1
  intl_phone_field: ^1.4.2
  dio:
  shared_preferences:
  flutter_secure_storage: ^3.3.5
  provider:
  image_picker:
  image_native_resizer:
  list_tile_switch:
  flutter_spinkit:
  connectivity:
  toast:
  flushbar:


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/lottie/

  fonts:
    - family: IranSans
      fonts:
        - asset: assets/fonts/iranSans/IRAN-Sans-Regular.ttf
        - asset: assets/fonts/iranSans/IRAN-Sans-Bold.ttf

    - family: OpenSans
      fonts:
        - asset: assets/fonts/opensans/OpenSans-Regular.ttf
